LD_FILE = boards/mimxrt1062-external-flash.ld
USB_VID = 0x16C0
USB_PID = 0x8888
USB_PRODUCT = "Teensy 4.0"
USB_MANUFACTURER = "PJRC"
USB_DEVICES = "CDC"

CHIP_VARIANT = MIMXRT1062DVJ6A
CHIP_FAMILY = MIMXRT1062

INTERNAL_FLASH_FILESYSTEM = 1

CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CSLAVE = 0
CIRCUITPY_NVM = 0
CIRCUITPY_ROTARYIO = 0

LONGINT_IMPL = MPZ
