USB_VID = 0x1209
USB_PID = 0x000C
USB_PRODUCT = "Michigan"
USB_MANUFACTURER = "Chickadee Tech"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 0
LONGINT_IMPL = NONE
SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = GD25Q16C

SUPEROPT_GC = 0
