// LEDs
//#define MICROPY_HW_LED_MSC              PIN_PA17 // red
// #define UART_REPL
#define USB_REPL

#define MICROPY_HW_BOARD_NAME "Xplain Pro SAMD21"
#define MICROPY_HW_MCU_NAME "samd21j18"

#define AUTORESET_DELAY_MS 500

#define MICROPY_PORT_A (PORT_PA24 | PORT_PA25 | PORT_PA13)
#define MICROPY_PORT_B (PORT_PB22 | PORT_PB16 | PORT_PB23)
#define SPI_FLASH_SERCOM      SERCOM5
#define SPI_FLASH_MUX_SETTING SPI_SIGNAL_MUX_SETTING_E
#define SPI_FLASH_PAD0_PINMUX PINMUX_PB16C_SERCOM5_PAD0
#define SPI_FLASH_PAD1_PINMUX PINMUX_UNUSED
#define SPI_FLASH_PAD2_PINMUX PINMUX_PB22D_SERCOM5_PAD2
#define SPI_FLASH_PAD3_PINMUX PINMUX_PB23D_SERCOM5_PAD3
#define SPI_FLASH_CS PIN_PA13
#define SPI_FLASH_BAUDRATE 1000000

#include "spi_flash.h"

#define BOARD_FLASH_SIZE (0x00040000 - 0x2000 - 0x010000)

#include "flash_AT25DF081A.h"
