#include "samd21_pins.h"

STATIC const mp_map_elem_t board_global_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P3), (mp_obj_t)&pin_PB00 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P4), (mp_obj_t)&pin_PB01 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P5), (mp_obj_t)&pin_PB06 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P6), (mp_obj_t)&pin_PB07 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P7), (mp_obj_t)&pin_PB02 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P8), (mp_obj_t)&pin_PB03 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P9), (mp_obj_t)&pin_PB04 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P10), (mp_obj_t)&pin_PB05 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P11), (mp_obj_t)&pin_PA08 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P12), (mp_obj_t)&pin_PA09 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P13), (mp_obj_t)&pin_PB09 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P14), (mp_obj_t)&pin_PB08 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P15), (mp_obj_t)&pin_PA05 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P16), (mp_obj_t)&pin_PA06 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P17), (mp_obj_t)&pin_PA04 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT1P18), (mp_obj_t)&pin_PA07 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P3), (mp_obj_t)&pin_PA10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P4), (mp_obj_t)&pin_PA11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P5), (mp_obj_t)&pin_PA20 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P6), (mp_obj_t)&pin_PA21 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P7), (mp_obj_t)&pin_PB12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P8), (mp_obj_t)&pin_PB13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P9), (mp_obj_t)&pin_PB14 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P10), (mp_obj_t)&pin_PB15 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P11), (mp_obj_t)&pin_PA08 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P12), (mp_obj_t)&pin_PA09 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P13), (mp_obj_t)&pin_PB11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P14), (mp_obj_t)&pin_PB10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P15), (mp_obj_t)&pin_PA17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P16), (mp_obj_t)&pin_PA18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P17), (mp_obj_t)&pin_PA16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT2P18), (mp_obj_t)&pin_PA19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P3), (mp_obj_t)&pin_PA02 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P4), (mp_obj_t)&pin_PA03 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P5), (mp_obj_t)&pin_PB30 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P6), (mp_obj_t)&pin_PA15 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P7), (mp_obj_t)&pin_PA12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P8), (mp_obj_t)&pin_PA13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P9), (mp_obj_t)&pin_PA28 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P10), (mp_obj_t)&pin_PA27 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P11), (mp_obj_t)&pin_PA08 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P12), (mp_obj_t)&pin_PA09 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P13), (mp_obj_t)&pin_PB11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P14), (mp_obj_t)&pin_PB10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P15), (mp_obj_t)&pin_PB17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P16), (mp_obj_t)&pin_PB22 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P17), (mp_obj_t)&pin_PB16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_EXT3P18), (mp_obj_t)&pin_PB23 },
	  
  
};
MP_DEFINE_CONST_DICT(board_module_globals, board_global_dict_table);
