LD_FILE = boards/samd51x20.ld
USB_VID = 0x239A
USB_PID = 0x8021
USB_PRODUCT = "pyoven"
USB_MANUFACTURER = "Chickadee Tech LLC"

INTERNAL_FLASH_FILESYSTEM = 1

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51
